{% set name = "mlt" %}
{% set version = "6.22.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/mltframework/mlt/releases/download/v{{ version }}/mlt-{{ version }}.tar.gz
  sha256: 3392d70c528d7f32e78329232b1b93a5a36b058215f664953090315132b797e5
  patches:
    # fix for GCC detection
    - configure.patch

build:
  number: 0
  skip: true  # [not linux]


requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
    - pkg-config
  host:
    - libxml2
    - libvorbis
    - ffmpeg
    - lame
    - alsa-lib
    - pulseaudio
    - ladspa
    - jack
    - fftw
  run:
    - libxml2
    - jack

test:
  commands:
    - melt --help

about:
  home: https://www.mltframework.org/
  license: LGPL-2.1
  license_family: GPL
  license_file: COPYING
  summary: MLT Multimedia Framework
  description: |
    Author, manage, and run multitrack audio/video compositions.
    The engine of a non-linear video editor that can be used in all sorts of apps,
    not just desktop video editors. MLT is an open source multimedia framework,
    designed and developed for television broadcasting. It provides a toolkit for
    broadcasters, video editors, media players, transcoders, web streamers and
    many more types of applications. The functionality of the system is provided
    via an assortment of ready to use tools, XML authoring components, and an
    extensible plug-in based API.
  doc_url: https://www.mltframework.org/docs/
  dev_url: https://github.com/mltframework/mlt

extra:
  recipe-maintainers:
    - scopatz
